### ISSUE TITLE
No module named 'esphome.components.qspi_dbi

### ISSUE THREAD

**Issue by Charly57** [ageurtse/esphome-clock#1]
I always get this error

INFO ESPHome 2024.10.2
INFO Reading configuration /config/esphome/esphome-web-2204b4.yaml...
INFO Unable to import component qspi_dbi.display: No module named 'esphome.components.qspi_dbi'
Failed config
display.qspi_dbi: [source /config/esphome/esphome-web-2204b4.yaml:273]
 Platform not found: 'display.qspi_dbi'.

What's going wrong?

and BTW:   platform: axs15231 was not found as well

**Comment by ageurtse** [comment]
Looking at your info, it seems that you didn't make use off ESPhome dev version, the code only compiles at this moment frome esphome 2024.11 and further. this version is available in the dev version

**Comment by Charly57** [comment]
okay I understand.
I started the program with 2024.10
so I have to wait 
Thank you for your information

**Comment by ageurtse** [comment]
From within home assistant you can also install esphome dev, then you could compile

**Comment by Charly57** [comment]
Thank you.
I have changed the code to an old driver and it works as well

**Comment by ageurtse** [comment]
When using development version ESPhome it should work
